services:
  app:
    image: hibobmaster/matrixchatgptbot:latest
    container_name: matrix_chatgpt_bot
    restart: always
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    volumes:
      - ./config.json:/app/config.json
      # use touch to create an empty file bot, for persist database only
      - ./bot:/app/bot
    networks:
      - matrix_network
  # api:
  # # bing api
  #   image: hibobmaster/node-chatgpt-api:latest
  #   container_name: node-chatgpt-api
  #   restart: always
  #   volumes:
  #     - ./settings.js:/var/chatgpt-api/settings.js
  #   networks:
  #     - matrix_network

networks:
  matrix_network:
