services:
  app:
    image: hibobmaster/matrixchatgptbot:latest
    container_name: matrix_chatgpt_bot
    restart: always
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    volumes:
      - ./config.json:/app/config.json

