services:
  app:
    image: hibobmaster/matrixchatgptbot:latest
    container_name: matrix_chatgpt_bot
    restart: unless-stopped
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      # use env file or config.json
      # - ./config.json:/app/config.json
      # use touch to create an empty file db, for persist database only
      - ./db:/app/db
      # import_keys path
      # - ./element-keys.txt:/app/element-keys.txt
    networks:
      - matrix_network
  api:
    # ChatGPT and Bing API
    image: hibobmaster/node-chatgpt-api:latest
    container_name: node-chatgpt-api
    restart: unless-stopped
    volumes:
      - ./settings.js:/app/settings.js
    networks:
      - matrix_network

  # pandora:
  #   # ChatGPT Web
  #   image: pengzhile/pandora
  #   container_name: pandora
  #   restart: unless-stopped
  #   environment:
  #     - PANDORA_ACCESS_TOKEN=xxxxxxxxxxxxxx
  #     - PANDORA_SERVER=0.0.0.0:8008
  #   networks:
  #     - matrix_network

networks:
  matrix_network:
